### PR TITLE
add parameters for embed_link

### PR DESCRIPTION
**Pull request by wfehr**
This PR adds the field 'parameters' to the VideoPlugin-model in order to append parameters to a given 'embed_link', for example "?rel=0" on a youtube-link.

### CODE REVIEW

**Comment by filwaitman** [comment]
Closes https://github.com/divio/djangocms-video/issues/39

**Comment by filwaitman** [comment]
Hey @wfehr! thanks for the PR!
Overall it looks good for python 3. We need to fix the import on python 2, though: 

```
>>> from urllib import parse
ImportError: cannot import name parse
```

I fixed that locally with the following patch:
```
diff --git a/djangocms_video/models.py b/djangocms_video/models.py
index f47fef2..0cbe427 100644
--- a/djangocms_video/models.py
+++ b/djangocms_video/models.py
@@ -9,7 +9,7 @@ from django.conf import settings
 from django.core.exceptions import ValidationError
 from django.utils.encoding import python_2_unicode_compatible
 from django.utils.translation import ugettext, ugettext_lazy as _
-from urllib import parse
+import sys
 
 from cms.models import CMSPlugin
 
@@ -18,6 +18,12 @@ from djangocms_attributes_field.fields import AttributesField
 from filer.fields.image import FilerImageField
 from filer.fields.file import FilerFileField
 
+if sys.version_info.major < 3:
+    from urlparse import urlparse, parse_qsl, urlunparse
+    from urllib import urlencode
+else:
+    from urllib.parse import urlparse, parse_qsl, urlencode, urlunparse
+
 
 # mp4, are required for full browser support
 ALLOWED_EXTENSIONS = getattr(
@@ -110,11 +116,11 @@ class VideoPlayer(CMSPlugin):
         return self._append_url_parameters(self.embed_link, self.parameters)
 
     def _append_url_parameters(self, url, params):
-        url_parts = list(parse.urlparse(url))
-        query = dict(parse.parse_qsl(url_parts[4]))
+        url_parts = list(urlparse(url))
+        query = dict(parse_qsl(url_parts[4]))
         query.update(params)
-        url_parts[4] = parse.urlencode(query)
-        return parse.urlunparse(url_parts)
+        url_parts[4] = urlencode(query)
+        return urlunparse(url_parts)
 
 
 @python_2_unicode_compatible
```

Can you fix that on your end?
You can, of course, do this in another ways. I'm just sharing my solution.
If you rather use six o `try: import xxx; except` approach, go for it. =]

Aside of this particular import I consider this PR approved.

**Comment by wfehr** [comment]
Hi @filwaitman,
thanks for your feedback!
I just made and tested the changes with your patch and pushed them.

Don't know why the checker didn't successfully build and test, is it because of the new changes or just bad luck?

**Comment by filwaitman** [comment]
You're welcome, @wfehr! Thanks for the quick review.

Hmmm travis/tox is not very well configured for this project. I'm glad there's an open PR for that as well. :laughing: 

So I think we're good to go now. @kinkerl do you wanna take a look as well?

**Pull request merged**
